services:
  mq:
    image: rabbitmq:3.13.7-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    env_file:
      - .env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq      -
    networks:
      - mq_net

networks:
  mq_net:
    driver: bridge
